Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy.linalg import norm
from numpy.random import random

def pagerank(G,eps=0.01):
	n,_ = G.shape
	x = random(n)

	#ensure probabilistic vector
	x /= x.sum()
	error = float('inf')
	idx = 0
	while error >= eps:
		xnext = G @ x
		error = norm(xnext-x)
		x     = xnext
		print(f'Iteration {idx}, Precision = {precision}')
	return x
	
pr = pagerank(google)
print(pr)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 19[0m
[1;32m     16[0m 		[38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mIteration [39m[38;5;132;01m{[39;00midx[38;5;132;01m}[39;00m[38;5;124m, Precision = [39m[38;5;132;01m{[39;00mprecision[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     17[0m 	[38;5;28;01mreturn[39;00m x
[0;32m---> 19[0m pr [38;5;241m=[39m [43mpagerank[49m[43m([49m[43mgoogle[49m[43m)[49m
[1;32m     20[0m [38;5;28mprint[39m(pr)

Cell [0;32mIn[5], line 16[0m, in [0;36mpagerank[0;34m(G, eps)[0m
[1;32m     14[0m 	error [38;5;241m=[39m norm(xnext[38;5;241m-[39mx)
[1;32m     15[0m 	x     [38;5;241m=[39m xnext
[0;32m---> 16[0m 	[38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mIteration [39m[38;5;132;01m{[39;00midx[38;5;132;01m}[39;00m[38;5;124m, Precision = [39m[38;5;132;01m{[39;00mprecision[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     17[0m [38;5;28;01mreturn[39;00m x

[0;31mNameError[0m: name 'precision' is not defined

